version: '3.8'
services:
  postgres:
    image: postgres:14.9-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-todoapp}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-todoapp}
      - POSTGRES_DB=${POSTGRES_DB:-todoapp}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
