# Generated by Django 3.2.21 on 2023-09-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todos',
        ),
    ]
