# Generated by Django 4.2.5 on 2023-09-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
