# Generated by Django 4.2.5 on 2023-09-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_rename_timestamp_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
